# 按键延时，单位为秒，必须必须必须根据脚本实际运行状况改成合适的数值
# 因为游戏内按键的识别范围在该脚本设定的图像检测范围的左边，且帧率等因素会影响下列数值
key_delay:
  古筝: 0.35
  通用: 0.38
  疆鼓: 0.49
  梆子: 0.52
  锣: 0.4
tesseract_path:
  Tesseract-OCR\tesseract.exe
resolution:
  width: 2560
  height: 1440